spring.application.name=backend
server.port=9090
# Toon SQL queries
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.datasource.url=jdbc:postgresql://localhost:5443/postgres?currentSchema=ordering
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

logging.level.sql=debug
logging.level.web=debug



#amq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password

#variable
restaurant-catalog-api.url=http://localhost:8080/api/restaurant
mollie.api.key=test_VM7rVdGQTVmNycvvb4ARDNsJa4mpWT
mollie.redirect.url=http://localhost:5173/payment-callback.html

# RabbitMQ Exchanges
rabbitmq.exchange.order=order-exchange
rabbitmq.exchange.restaurant-response=restaurant-response-exchange
rabbitmq.exchange.delivery-response=delivery-response-exchange

# RabbitMQ Queues
rabbitmq.queue.order-accept=order-accept-queue
rabbitmq.queue.order-deny=order-deny-queue
rabbitmq.queue.order-ready=order-ready-queue
rabbitmq.queue.pickedup=pickedup-response-queue
rabbitmq.queue.deliverd=deliverd-response-queue

# RabbitMQ Routing Keys
rabbitmq.routing-key.order-accept=order.accept.*
rabbitmq.routing-key.order-deny=order.deny.*
rabbitmq.routing-key.order-ready=order.ready.*
rabbitmq.routing-key.order-pickedup=order.pickedup.*
rabbitmq.routing-key.order-deliverd=order.deliverd.*
rabbitmq.exchange.order.place.routing.key=order.place.*